#!/usr/bin/env bash
# printing "Best School" 10 times  but for the 9th iteration, displays Best School and then Hi

for (( i=1; i<=100; i++ ))
do
	if [ $((i%15)) -eq 0 ]
	then
		echo FizzBuzz
	elif [ $((i%5)) -eq 0 ]
	then
		echo Buzz
	elif [ $((i%3)) -eq 0 ]
	then
		echo Fizz
	else
		echo "$i"
	fi
done
