#!/usr/bin/env bash
# printing "Best School" 10 times  but for the 9th iteration, displays Best School and then Hi

i=0

while [ $i -le 11 ]
do
echo Hour: $i
j=1
while [ $j -le 59 ]
do
echo $j

j=$((j+1))
done

i=$((i+1))
done
