#!/usr/bin/env bash
# printing "Best School" 10 times  but for the 9th iteration, displays Best School and then Hi


if [ -a school ]
then
	echo school file exists
	if [ -s school ]
	then
		echo school file is not empty
	else
		echo school file is empty
	fi
	if [ -f school ]
	then
		echo school is a regular file
	fi
else
	echo school file does not exist
fi
